### ISSUE TITLE
Citation ?

### ISSUE THREAD

**Issue by sbhakat** [jhenin/Methods-for-enhanced-sampling-and-free-energy-calculations#1]
Great job folks. I believe a citation of my review https://arxiv.org/abs/2112.03202 is well deserving in the following part:

`We do not review methods that aim to extract collective variables from simulations. See instead [1–3] for recent reviews of the topic. `

**Comment by jhenin** [comment]
Thank you for your suggestion. After discussing it, we have decided to only include final, peer-reviewed versions of reviewed articles.

**Comment by sbhakat** [comment]
The article is online and peer-reviewed. Please see the link: https://pubs.rsc.org/en/content/articlehtml/2022/RA/D2RA03660F

**Comment by jhenin** [comment]
Ah, I see that it was accepted just after the revision for this was re-submitted, that's too bad. Since this is a live review though, there will be updates in the future where we get chances to include more references.
