### ISSUE TITLE
GaMD has adaptive biasing potential

### ISSUE THREAD

**Issue by MiaoLab20** [jhenin/Methods-for-enhanced-sampling-and-free-energy-calculations#6]
Thanks to All for your "living" review of enhanced sampling methods!

I wanted to point out that GaMD does have adaptive biasing potential during the simulations, and should not be put in section 6.

As shown in the GaMD publications (Refs. 81 and 82) and GaMD website (https://miaolab.ku.edu/GaMD/theory.html), the GaMD boost potential is a harmonic function of the system potential energy at any given time t. Thus it will "adaptively" adjust its value at different simulation frames with updated system potential energy values.

Moreover, we generally run initial short conventional MD to collect potential statistics and GaMD equilibration to optimize the threshold energy E for applying boost potential and the harmonic force constant. Then that will give us optimal acceleration parameters to run the GaMD production simulations. You can find an illustration of the algorithm at: https://miaolab.ku.edu/GaMD/manual.html.

I hope this makes sense and you can put GaMD in the right category of enhanced sampling methods. Thank you!

**Comment by jhenin** [comment]
Thank you for this remark! Indeed, this is an oversight that we need to fix. As you can see, there is so much ground to cover in this review that it is difficult not to miss anything, but thanks to feedback like this one, we can keep making it better.

I think the relevant section to describe GaMD would be "Adaptive Biasing Potential Methods Using the Potential Energy as a Collective Variable", which would allow for an interesting parallel with Wang-Landau and the well-tempered ensemble.

**Comment by MiaoLab20** [comment]
Thanks for your reply, @jhenin! It's a great review. It's nice that you can update it so easily!

**Comment by valsson** [comment]
Hello Yinglong! 

Thanks for your comment. I agree with Jérôme that it would make sense to mention GaMD (and also accelerated MD) in the "Adaptive Biasing Potential Methods Using the Potential Energy as a Collective Variable" in Section 7. 

However, I am not sure that the bias potential in GaMD is an adaptive biasing potential according to the definition that we use in the review, and how I like to think about it. 

If I understand equation 1.1 in https://miaolab.ku.edu/GaMD/theory.html, during a simulation (e.g., the production one), the E and k parameters are kept fixed. Is my understanding correct? Generally, I would consider an adaptive biasing potential where the parameters of the bias potential are changed during the simulation, e.g., the parameters of the bias potential are time-dependent. Thus, if E and k are fixed during a simulation, the bias potential within that single simulation would not be an adaptive biasing potential. 

However, I can agree that the whole procedure of running multiple simulations to adjust the boost parameters E and k makes the whole GaMD procedure an adaptive method. Therefore, it makes sense to discuss it in Section 7. 

Please let me know if you think I am misunderstanding something or if you do not agree with me. 

Omar

**Comment by MiaoLab20** [comment]
Thanks for your insightful thoughts, Omar!

I guess we call "Adaptive Biasing Potential", not "Adaptive Biasing/Boosting/Acceleration Parameters". Broadly speaking, once the biasing potential is time-dependent, it may be adaptive (to the present system state or potential energy). That's my intuitive thought, but yes, it's up to how you define it in the review.

On the same note, the E and k parameters are constantly updated during GaMD equilibration. I actually had an earlier version of GaMD that simply runs "equilibration" until the end of the simulation (so truly adaptive in terms of both the biasing potential and acceleration parameters). However, it didn't show significantly improved sampling power, while at the same time the simulation efficiency/speed was slightly reduced and the biasing potential appeared more noisy for reweighting. That eventually led to the current version of GaMD that runs equilibration to optimize the E and k parameters and then production simulation.

Hope this helps and I'm open to discuss more!

All the best,
Yinglong

**Comment by jhenin** [comment]
Thank you Yinglong, we have updated the text with insight from this conversation.
