### ISSUE TITLE
Issues/typos to fix in proofs

### ISSUE THREAD

**Issue by valsson** [jhenin/Methods-for-enhanced-sampling-and-free-energy-calculations#7]
I noticed some issues and typos that need to be fixed in the proof stage or the next revision. To keep track, we can add them to this issue as comments

**Comment by valsson** [comment]
https://github.com/jhenin/Methods-for-enhanced-sampling-and-free-energy-calculations/blob/75e8094ac19cb9aa6eccce0382b1a6f250db7c54/review.tex#L166

Fix repeated which in "which methods which"

**Comment by valsson** [comment]
https://github.com/jhenin/Methods-for-enhanced-sampling-and-free-energy-calculations/blob/75e8094ac19cb9aa6eccce0382b1a6f250db7c54/review.tex#L280

Change {Molecular dynamics simulation} to {\paragraph{Molecular dynamics simulation}}

**Comment by mrshirts** [comment]
Will be fine to fix them in proof.

**Comment by valsson** [comment]
Closed via e9afa925a0df51cb2bc1356e437acf4bbaac0089
